# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-16 20:02
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180616_1836'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='conversation',
            name='tags',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='conversation',
            name='title',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
