# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-16 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180616_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('closed', 'Closed'), ('cancelled', 'Cancelled'), ('active', 'Active'), ('suspended', 'Suspended')], default='pending', max_length=20),
        ),
    ]
